backend:
  name: netlify-api
  url: http://localhost:8080

production:
  backend:
    name: github-api
    repo: webriq/webriqpage-minisite-premium # Updated repo details ### Original: webriq/webriqpage-minisite-business # Updated repo details ### Original: owner/repo # Path to your Github repository
    branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go
public_folder: "assets"

collections: # A list of collections the CMS should be able to edit
  - name: "sitedata"
    label: "Site Information"
    files:
      - name: "sitedata"
        label: "Site Information"
        file: "data/site.json"
        description: "edit site information"
        fields:
          - label: "Site Information"
            name: "sitedata"
            widget: "list"
            fields:
              - {label: "Favicon", name: "icon", widget: "image", media_folder: "assets/img"}
              - {label: "Site Logo", name: "logo", widget: "image", media_folder: "assets/img"}
              - {label: "Site name", name: "sitename", widget: "string"}
              - {label: "Website Description", name: "metadesc", widget: "string"}
              - {label: "Author", name: "metauthor", widget: "string"}
              - {label: "Keywords", name: "metakeyword", widget: "string"}
              - {label: "Footer", name: "footer", widget: "markdown"}
              - {label: "Add header image", name: "header_background", widget: "image", media_folder: "assets/img"}
              - {label: "Google Analytics", name: "analytics", widget: "markdown"}
              - {label: "Services title", name: "services_title", widget: "string"}
              - {label: "Services subheading", name: "services_subheading", widget: "string"}

          - label: "Services - Section"
            name: "services"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Body", name: "body", widget: "string"}
              - {label: "icon", name: "icon", widget: "markdown"}
              - {label: "Class", name: "class", widget: "string"}

          - label: "Footer - Section"
            name: "footerdata"
            widget: "list"
            fields:
              - {label: "First column html", name: "first", widget: "markdown"}
              - {label: "Second column html", name: "second", widget: "markdown"}
              - {label: "Third column html", name: "third", widget: "markdown"}              

  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog"  # Used in the UI, ie.: "New Post"
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Writer / author", name: "author", widget: "string"}
      - {label: "Tags", name: "leadtag", widget: "string"}
      - {label: "Main Image", name: "mainimage", widget: "image", class: "image thumbnail", media_folder: "assets/img/blog"}
      - {label: "Thumbnail", name: "banner", widget: "image", class: "image featured", media_folder: "assets/img/blog/featured"}
      - {label: "Short description", name: "shortdesc", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Date", name: "date", widget: "date"}

  # Navigation
  - name: "navigation"
    label: "Main navigation & social link"
    files:
      - name: "navigation"
        label: "Main navigation & social link"
        file: "data/menu.json"
        description: "Add Main navigation & social link entries here"
        fields:
          - label: "Navigation List"
            name: "navigation"
            widget: "list"
            fields:
              - {label: "Item Name", name: "item", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {label: "Alt text", name: "alt", widget: "string"}
              - {label: "Custom class", name: "class", widget: "string"}
          - label: "Social Media"
            name: "social"
            widget: "list"
            fields:
              - {label: "Item Name", name: "item", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {label: "Alt text", name: "alt", widget: "string"}
              - {label: "Custom class", name: "class", widget: "string"}
              - {label: "Add icon", name: "icon", widget: "markdown"}